#!/usr/bin/env python3
"""Fix remaining names without definitions."""
import json
import re
import xml.etree.ElementTree as ET
from pathlib import Path

BASE_DIR = Path(__file__).parent.parent

with open(BASE_DIR / 'data' / 'bible_names.json', 'r', encoding='utf-8') as f:
    data = json.load(f)
names = data['names']

ns = 'http://openscriptures.github.com/morphhb/namespace'
tree = ET.parse(r'C:\Users\Tammy Casey\Documents\AI PROJECTS\PEER\morphhb-master\HebrewStrong.xml')
root = tree.getroot()

def ft(e):
    if e is None: return ''
    parts = [e.text or '']
    for c in e:
        parts.append(c.text or '')
        parts.append(c.tail or '')
    return re.sub(r'\s+', ' ', ' '.join(parts)).strip()

strongs = {}
for entry in root:
    sid = entry.attrib.get('id', '')
    if not sid: continue
    w = entry.find(f'{{{ns}}}w')
    source = entry.find(f'{{{ns}}}source')
    meaning = entry.find(f'{{{ns}}}meaning')
    usage = entry.find(f'{{{ns}}}usage')
    strongs[sid] = {
        'hebrew': (w.text or '').strip() if w is not None else '',
        'pron': w.attrib.get('pron', '') if w is not None else '',
        'xlit': w.attrib.get('xlit', '') if w is not None else '',
        'source_text': ft(source),
        'meaning': ft(meaning),
        'usage': ft(usage),
    }

# Build ALL lookups
all_by_hebrew = {}
for sid, e in strongs.items():
    clean = re.sub(r'[\u0591-\u05C7]', '', e['hebrew'])
    if clean and clean not in all_by_hebrew:
        all_by_hebrew[clean] = sid

all_by_english = {}
for sid, e in strongs.items():
    for field in ['usage', 'meaning']:
        text = e.get(field, '')
        for eng in re.findall(r'([A-Z][a-z]{2,})', text):
            if eng not in all_by_english:
                all_by_english[eng] = sid

# Manual definitions for important names
MANUAL = {
    'Nephilim': 'Fallen ones; giants. From naphal (to fall).',
    'Amorites': 'Mountain dwellers. From amar (to say).',
    'Hivites': 'Villagers. Related to chavvah (tent village).',
    'Horites': 'Cave dwellers. From chor (cave).',
    'Horite': 'Cave dweller. From chor (cave).',
    'Kenites': 'Smiths, metalworkers. From qayin (spear/smith).',
    'Cretans': 'People of Crete. Also called Cherethites.',
    'Zuzim': 'Roving creatures. A people east of Jordan.',
    'Kittim': 'Cypriots. Descendants of Javan.',
    'Rodanim': 'People of Rhodes. Variant of Dodanim.',
    'Anamim': 'An Egyptian people. Descendants of Mizraim.',
    'Lehabim': 'Flames, Libyans. Descendants of Mizraim.',
    'Casluhim': 'An Egyptian people, forebears of Philistines.',
    'Aramean': 'From Aram (highland/Syria).',
    'Arameans': 'People of Aram (highland/Syria).',
    'Hebrews': 'Those who crossed over. From avar (to cross).',
    'Levites': 'Descendants of Levi (joined/attached).',
    'Danites': 'Tribe of Dan (judge).',
    'Danite': 'Of the tribe of Dan (judge).',
    'Gadites': 'Tribe of Gad (fortune).',
    'Gadite': 'Of the tribe of Gad (fortune).',
    'Judites': 'People of Judah (praise).',
    'Jews': 'People of Judah (praise). From yadah (to praise).',
    'Nile': 'The great river of Egypt. Hebrew: Ye-or.',
    'Sheol': 'The grave, underworld, place of the dead.',
    'Satan': 'Adversary, accuser. From satan (to oppose).',
    'Azazel': 'Scapegoat. Possibly: removal, or goat of departure.',
    'Phicol': 'Mouth of all. Commander of Abimelech.',
    'Maacah': 'Oppression, pressure. A region and persons.',
    'Hanoch': 'Dedicated, initiated. Same root as Enoch.',
    'Paddan': 'A field, plateau. Region of Aram-Naharaim.',
    'Mizpah': 'Watchtower. From tsaphah (to watch).',
    'Negeb': 'The dry south, the Negev desert region.',
    'Goiim': 'Nations, peoples. Plural of goy (nation).',
    'Dammesek': 'Damascus. Ancient Syrian capital.',
    'Gaza': 'Strong, fortified. A Philistine city.',
    'Ehyeh': 'I AM, I will be. Divine self-designation.',
    'Reeds': 'Sea of Reeds (Yam Suph). The Red Sea crossing.',
    'Purim': 'Lots. Feast commemorating Esther.',
    'Nisan': 'First month of Hebrew calendar. Spring.',
    'Urim': 'Lights. Priestly oracle with Thummim.',
    'Holies': 'Holy of Holies. The inner sanctuary.',
    'Greece': 'Yavan. Land of Greeks/Ionians.',
    'Pishon': 'Freely flowing. First river of Eden.',
    'Sukkoth': 'Booths, shelters. From sukkah (booth).',
    'Baals': 'Lords, masters. Plural of Baal.',
    'Asheroth': 'Sacred poles/groves. Canaanite worship.',
    'Cun': 'Established, fixed. A city of Hadadezer.',
    'Abrek': 'Kneel! A command of honor.',
    'Goren': 'Threshing floor. A place of harvest.',
    'Puvah': 'Mouth, utterance. Son of Issachar.',
    'Arkites': 'People of Arka, a Phoenician city.',
    'Sinites': 'People of Sin, a Canaanite settlement.',
    'Letushim': 'Hammered ones. Descendants of Dedan.',
    'Leummim': 'Nations, peoples. Descendants of Dedan.',
    'Jabesh': 'Dry. A city in Gilead.',
    'Hivite': 'Villager. A Canaanite people.',
    'Cherith': 'Cut, gorge. A brook east of Jordan.',
    'Ichabod': 'No glory. From i (not) + kavod (glory).',
    'Abib': 'Green ears of grain. First month name.',
    'Hilkiah': 'My portion is YHWH.',
    'Asherite': 'Of the tribe of Asher (happy/blessed).',
    'Baali': 'My lord/master. A title for God rejected by Hosea.',
    'Biblical': 'Of the Bible. Not a proper name.',
    'Dagan': 'Grain, Dagon. Philistine deity.',
    'Amnon': 'Faithful. Firstborn son of David.',
    'Abshai': 'Father of gift. Variant of Abishai.',
    'Chimhan': 'Longing. Companion of David.',
    'Eznite': 'The spear. A designation of Adino.',
    'Ezrahite': 'Of Zerah/Ezrah. A family designation.',
    'Bul': 'Rain, produce. Eighth month name.',
    'Ethanim': 'Enduring. Seventh month name.',
    'Aaronite': 'Descendant of Aaron, the priest.',
    'Molech': 'King. A Canaanite deity of child sacrifice.',
    'Edomites': 'Descendants of Esau/Edom (red).',
    'Libnites': 'Descendants of Libni (white).',
    'Mahlites': 'Descendants of Mahli (sick/weak).',
    'Carmites': 'Descendants of Carmi (vineyard).',
    'Haggites': 'Descendants of Haggi (festive).',
    'Oznites': 'Descendants of Ozni (attentive).',
    'Arelites': 'Descendants of Areli.',
    'Punites': 'Descendants of Puvah.',
    'Elonites': 'Descendants of Elon (oak).',
    'Eranites': 'Descendants of Eran (watcher).',
    'Belaites': 'Descendants of Bela (swallowed).',
    'Ardites': 'Descendants of Ard.',
    'Ishvites': 'Descendants of Ishvi (level).',
    'Gunites': 'Descendants of Guni (protected).',
    'Arodites': 'Descendants of Arod.',
    'Calebite': 'Of Caleb (dog/bold).',
    'Tekoite': 'Person from Tekoa (trumpet blast).',
    'Tekoites': 'People from Tekoa.',
    'Gilonite': 'Person from Giloh (exile).',
    'Horonite': 'Person from Horonaim.',
    'Archite': 'Person from Erech/Arka.',
    'Archites': 'People from Erech/Arka.',
    'Harodite': 'Person from Harod (trembling).',
    'Ahohite': 'Descendant of Ahoah.',
    'Ahohi': 'Brotherly. Variant of Ahoah.',
    'Arbite': 'Person from Arab (ambush).',
    'Paltite': 'Person from Beth-pelet (escape).',
    'Pelonite': 'A certain one, unnamed.',
    'Ithrite': 'Descendant of Ithran (abundance).',
    'Ithrites': 'Descendants of Ithran.',
    'Jairite': 'Descendant of Jair (enlightener).',
    'Izrahite': 'Descendant of Izrah (shining).',
    'Gederite': 'Person from Geder (wall).',
    'Gizonite': 'Person from Gizon.',
    'Mithnite': 'Person from Methen.',
    'Mahavite': 'Of the village.',
    'Tizite': 'Person from Tiz.',
    'Aroerite': 'Person from Aroer (ruins).',
    'Hararite': 'Person from Harar (mountain).',
    'Asaphite': 'Descendant of Asaph (gatherer).',
    'Timnite': 'Person from Timnah (portion).',
    'Gittites': 'People from Gath (winepress).',
    'Gazites': 'People from Gaza (strong).',
    'Garmite': 'Descendant of Gerem (bone).',
    'Zorites': 'People from Zorah.',
    'Puthites': 'A family of Kiriath-jearim.',
    'Matrites': 'Descendants of Matri.',
    'Ziphites': 'People from Ziph.',
    'Gizrites': 'People from Gezer.',
    'Anakites': 'Giants. Descendants of Anak (long-necked).',
    'Anokites': 'Variant of Anakites.',
    'Judean': 'Person from Judah.',
    'Judeans': 'People from Judah.',
    'Cushite': 'Person from Cush/Ethiopia.',
    'Cushites': 'People from Cush/Ethiopia.',
    'Maachite': 'Person from Maacah.',
    'Agagite': 'Descendant of Agag.',
    'Temanite': 'Person from Teman (south).',
    'Shuhite': 'Descendant of Shuah.',
    'Tyrian': 'Person from Tyre.',
    'Carians': 'Mercenary soldiers from Caria.',
    'Elamites': 'People from Elam.',
    'Libyans': 'People from Libya/Lubim.',
    'Sukkites': 'Tent-dwellers. An African people.',
    'Persians': 'People from Persia/Paras.',
    'Sabaites': 'People from Saba/Sheba.',
    'Sinim': 'A distant people, possibly Chinese.',
    'Syenians': 'People from Syene (Aswan).',
    'Ionians': 'Greeks. From Yavan.',
    'Mede': 'Person from Media.',
    'Susa': 'Lily. Capital of Persia.',
    'Aswan': 'A city in upper Egypt.',
    'India': 'The land of the Indus.',
    'Memphis': 'Egyptian city. Haven of the good.',
    'Siloam': 'Sent, sending. A pool in Jerusalem.',
    'Immanuel': 'God is with us. From immanu (with us) + El (God).',
    'Diphath': 'Variant of Riphath. Son of Gomer.',
    'Sabta': 'Variant of Sabtah. Son of Cush.',
    'Raama': 'Variant of Raamah. Thunder.',
    'Shuhah': 'Pit, depression. A descendant of Judah.',
    'Ashhur': 'Variant of Asshur. Black.',
    'Meshah': 'Freedom, withdrawal.',
    'Bethzur': 'House of rock.',
    'Recah': 'A town in Judah.',
    'Ge': 'Valley.',
    'Menuhoth': 'Resting places.',
    'Menuhah': 'Rest, quietness.',
    'Ebiasaph': 'Father has gathered.',
    'Ibsam': 'Fragrant, pleasant.',
    'Ishhod': 'Man of majesty.',
    'Eleadah': 'God has adorned.',
    'Elioenai': 'Unto God are my eyes.',
    'Sachiah': 'Protected by YHWH.',
    'Izliah': 'YHWH delivers.',
    'Iphdeiah': 'YHWH redeems.',
    'Ishmaiah': 'YHWH hears.',
    'Beeliada': 'The Lord knows. Variant of Eliada.',
    'Obededom': 'Servant of Edom.',
    'Jahzeiah': 'YHWH sees.',
    'Izziah': 'YHWH sprinkles.',
    'Ahzai': 'My holder. Shortened form.',
    'Amashsai': 'Burdensome.',
    'Siah': 'Variant of Siaha.',
    'Hacaliah': 'Wait for YHWH.',
    'Hodeiah': 'Splendor of YHWH.',
    'Pelaliah': 'YHWH judges.',
    'Melicu': 'Variant of Malluch (counselor).',
    'Meramoth': 'Variant of Meremoth (heights).',
    'Meconah': 'A base, foundation.',
    'Nathanel': 'Gift of God. Variant of Nethanel.',
    'Jedithun': 'Variant of Jeduthun (praising).',
    'Jehieli': 'Variant of Jehiel (God lives).',
    'Hilez': 'Variant of Hilkiah (portion of YHWH).',
    'Shirtai': 'A Sharonite overseer.',
    'Shimrith': 'Variant of Shimrith (watchful).',
    'Zephat': 'Variant of Zephath (watchtower).',
    'Dodavahu': 'Loved by YHWH.',
    'Hathach': 'A eunuch of King Ahasuerus.',
    'Vaizatha': 'Son of Haman. Persian name.',
    'Hagrites': 'Descendants of Hagar.',
    'Unpitied': 'Lo-ruhamah. Not pitied.',
    'Shulem': 'Variant of Shulammite. Peaceful.',
    'Lebo': 'Entrance. As in Lebo-Hamath.',
    'Kiriath': 'City. As in Kiriath-jearim.',
    'Jabesh': 'Dry. A city in Gilead.',
    'Nashim': 'Women. Plural of ishah.',
    'Midbar': 'Wilderness, desert.',
    'Jeshimon': 'Wasteland, desolation.',
    'Havvoth': 'Villages, tent-camps.',
    'Pene': 'Face of. As in Penuel.',
    'Reba': 'A fourth part. A Midianite king.',
    'Mishneh': 'Second quarter. Part of Jerusalem.',
    'Metheg': 'Bridle. As in Metheg-ammah.',
    'Abronah': 'A passage, crossing. A desert camp.',
    'Kehelath': 'Assembly. A desert camp.',
    'Gulloth': 'Springs, bowls.',
    'Kephirim': 'Young lions. A town of Benjamin.',
    'Shaalbon': 'Place of foxes.',
    'Pashhur': 'Freedom, prosperity. A priestly name.',
    'Hushi': 'Variant of Hushai. Hasty.',
    'Gibbar': 'Strong man, hero.',
    'Shalmai': 'My peace.',
    'Jelahi': 'Variant of Jaalah.',
    'Addon': 'Lord, master.',
    'Tatam': 'A town in Judah.',
    'Kulon': 'Sustenance. A town in Judah.',
    'Karem': 'Vineyard. A town in Judah.',
    'Lahmas': 'Bread, food. A town in Judah.',
    'Shion': 'Ruin. A town in Issachar.',
    'Mehebel': 'Benefited by God.',
    'Lakkum': 'A town in Naphtali.',
    'Ithlah': 'Hanging. A town in Dan.',
    'Dobrath': 'Pasture. Variant of Daberath.',
    'Kartan': 'City. A Levitical city.',
    'Kartah': 'City. A Levitical city.',
    'Dimnah': 'Dung. A Levitical city.',
    'Socho': 'Variant of Socoh. Thorny hedge.',
    'Tochen': 'A measure. A town in Simeon.',
    'Jaakobah': 'He follows. Variant of Jacob.',
    'Meunim': 'Habitations. A people of Arabia.',
    'Janai': 'YHWH answers.',
    'Jacan': 'Troublesome.',
    'Rimmono': 'Variant of Rimmon. Pomegranate.',
    'Shuppim': 'Serpents. A Levite gatekeeper.',
    'Pispa': 'Disappearing.',
    'Rizia': 'Delight.',
    'Topheth': 'Place of fire. A site of child sacrifice in Hinnom.',
    'Harsith': 'Potsherd. As in Potsherd Gate.',
    'Dilan': 'A town in Judah.',
    'Huzzab': 'It is decreed. Uncertain Nineveh reference.',
    'Nahar': 'River. As in Aram-Naharaim.',
    'Neharim': 'Rivers. As in Aram-Naharaim.',
    'Puzai': 'A river in Assyria.',
    'Shebat': 'Eleventh month of Hebrew calendar.',
    'Sivan': 'Third month of Hebrew calendar.',
    'Elul': 'Sixth month of Hebrew calendar.',
    'Thammim': 'Variant of Thummim. Perfections.',
    'Zecher': 'Variant of Zechariah. Remembrance.',
    'Taharea': 'Variant of Tarea.',
    'Dammim': 'Bloods. As in Pas-dammim.',
    'Hachmoni': 'Wise. Father of Jehiel.',
    'Sippai': 'Variant of Saph. Threshold.',
    'Shophach': 'Pouring out. An Aramean commander.',
    'Zizah': 'Variant of Ziza. Abundance.',
    'Seorim': 'Barley. Head of a priestly division.',
    'Hakkoz': 'The thorn. Head of a priestly division.',
    'Jehezkel': 'God strengthens. Variant of Ezekiel.',
    'Shubael': 'Captive of God. A Levite.',
    'Jehdeiah': 'Unity of YHWH.',
    'Shoham': 'Onyx stone. A Levite.',
    'Bukkiah': 'Wasting of YHWH. A temple singer.',
    'Othni': 'My strength. Son of Shemaiah.',
    'Rephael': 'God has healed.',
    'Zabdiel': 'Gift of God.',
    'Adlai': 'My witness. Father of Shaphat.',
    'Zaham': 'Loathing. Son of Rehoboam.',
    'Miniamin': 'From the right hand.',
    'Coniah': 'YHWH establishes. Variant of Jehoiachin.',
    'Hasrah': 'Splendor. Variant of Harhas.',
    'Igdaliah': 'YHWH is great.',
    'Zeph': 'Shortened form of Zephaniah.',
    'Mahseiah': 'YHWH is a refuge.',
    'Jezaniah': 'YHWH hears.',
    'Ephai': 'Gloomy, birdlike.',
    'Hophra': 'An Egyptian pharaoh.',
    'Diblaim': 'Double fig cakes.',
    'Pannag': 'A type of pastry or confection.',
    'Chilmad': 'An Assyrian trading city.',
    'Zemar': 'A Phoenician city.',
    'Gammad': 'Warriors, dwarfs.',
    'Ashpenaz': 'Chief of Nebuchadnezzar eunuchs.',
    'Berathah': 'Variant of Berothai. Wells.',
    'Tamid': 'Continual. The daily offering.',
    'Darom': 'The south.',
    'Buzi': 'My contempt. Father of Ezekiel.',
    'Diblah': 'Variant of Riblah. Fig cake.',
    'Karnaim': 'Two horns. A city in Bashan.',
    'Sikkuth': 'A pagan deity.',
    'Saturn': 'Kiyyun. A star-god.',
    'Achor': 'Trouble. The valley of Achor.',
    'Besor': 'Cool, refreshing. A brook in the Negev.',
    'Siphmoth': 'Fruitful places.',
    'Athach': 'A town in Judah.',
    'Giah': 'A waterfall, spring.',
    'Bithron': 'A ravine, gorge.',
    'Bahurim': 'Young men. A village near Jerusalem.',
    'Becorath': 'First-born. An ancestor of Saul.',
    'Zelzah': 'Shadow of protection. Near Rachel tomb.',
    'Migron': 'Precipice. A place near Gibeah.',
    'Bozez': 'Shining. A crag near Michmash.',
    'Michmas': 'Variant of Michmash. Hidden.',
    'Zeboim': 'Hyenas, gazelles. A valley.',
    'Adoniram': 'My lord is exalted.',
    'Kue': 'Cilicia. A region of Asia Minor.',
    'Zeredah': 'Fortress, cooling. Home of Jeroboam.',
    'Tiphsah': 'A ford, crossing. A city on the Euphrates.',
    'Aloth': 'Variant of Bealoth. Mistresses.',
    'Millo': 'Rampart, fill. A fortification in Jerusalem.',
    'Pharpar': 'Swift. A river of Damascus.',
    'Gur': 'A whelp, cub. A place near Ibleam.',
    'Silla': 'A place in Jerusalem.',
    'Halah': 'A region of Assyria.',
    'Cuthah': 'Crushing. A Babylonian city.',
    'Ashima': 'A deity worshipped by people of Hamath.',
    'Tartak': 'A deity of the Avvites.',
    'Tartan': 'An Assyrian military title.',
    'Ivvah': 'Variant of Avva. An Assyrian city.',
    'Rezeph': 'Hot stone. An Assyrian-conquered city.',
    'Telassar': 'Hill of Asshur. An Assyrian region.',
    'Jotbah': 'Pleasantness.',
    'Gimzo': 'Sycamores. A city in Judah.',
    'Conaniah': 'YHWH has established.',
    'Tabbaoth': 'Rings, signet rings.',
    'Ecbatana': 'Persian capital. Place of gathering.',
    'Casiphia': 'Silvery. A place in Babylon.',
    'Kelaiah': 'Dwarf, insignificant.',
    'Athlai': 'YHWH is exalted.',
    'Chelal': 'Completeness.',
    'Sharai': 'My prince.',
    'Jadon': 'He will judge.',
    'Harhaiah': 'Fear of YHWH.',
    'Harumaph': 'Flat-nosed.',
    'Azbuk': 'Strong devastation.',
    'Ananiah': 'YHWH has covered.',
    'Uzai': 'My strength.',
    'Gashmu': 'Variant of Geshem. Rain.',
    'Perida': 'Variant of Peruda. Grain.',
    'Bunni': 'My understanding.',
    'Azaniah': 'YHWH has heard.',
    'Beninu': 'Our son.',
    'Azzur': 'Helpful.',
    'Ahiah': 'Brother of YHWH.',
    'Hazaiah': 'YHWH has seen.',
    'Joed': 'YHWH is witness.',
    'Sallai': 'Variant of Sallu. Weighed.',
    'Micha': 'Who is like YHWH? Variant of Micah.',
    'Gishpa': 'Caress, attentive.',
    'Aija': 'Variant of Ai. Heap of ruins.',
    'Mehuman': 'Faithful. A Persian eunuch.',
    'Carcas': 'A Persian eunuch.',
    'Bigthana': 'Gift of God. A Persian eunuch.',
    'Harbonah': 'Donkey-driver. A Persian eunuch.',
    'Dalphon': 'Dripping. A son of Haman.',
    'Aspatha': 'Horse-given. A son of Haman.',
    'Poratha': 'Fruitful. A son of Haman.',
    'Adalia': 'I shall be drawn up. A son of Haman.',
    'Aridatha': 'Great birth. A son of Haman.',
    'Arisai': 'Lion-like. A son of Haman.',
    'Barachel': 'God has blessed.',
    'Jakeh': 'Pious, obedient.',
    'Keziah': 'Cassia. A daughter of Job.',
    'Calno': 'Fortress. An Assyrian-conquered city.',
    'Eglaim': 'Two pools. A Moabite city.',
    'Shoa': 'Rich, noble. An eastern people.',
    'Malchiah': 'My king is YHWH.',
    'Gemariah': 'YHWH has accomplished.',
    'Neriah': 'Lamp of YHWH.',
    'Cushi': 'Ethiopian, Cushite.',
    'Jehucal': 'YHWH is able.',
    'Jahzah': 'Variant of Jahaz. Trodden down.',
    'Hara': 'Mountainous. An Assyrian region.',
    'Hananel': 'God is gracious. A tower in Jerusalem.',
    'Moseroth': 'Bonds, chastisements. A desert camp.',
    'Gudgod': 'Cleft. A desert camp. Variant: Hor-haggidgad.',
    'Shepham': 'A bare place. A border town.',
    'Riblah': 'Fertility. A town in Syria.',
    'Chislon': 'Hope, trust.',
    'Shiphtan': 'Judging.',
    'Parnach': 'Delicate.',
    'Azzan': 'Strong.',
    'Shelomi': 'My peace.',
    'Bezer': 'Fortified, gold ore. A city of refuge.',
    'Beeroth': 'Wells. A Hivite city.',
    'Gibeath': 'Hill. Variant of Gibeah.',
    'Achan': 'Troubler. Who took from the devoted things.',
    'Zabdi': 'My gift.',
    'Shebarim': 'Breaches, ruins.',
    'Hoham': 'Whom YHWH impels. King of Hebron.',
    'Piram': 'Wild, swift. King of Jarmuth.',
    'Sella': 'Variant of Sela (rock).',
    'Lachish': 'Invincible. A Canaanite city.',
    'Eglon': 'Calf-like. A Moabite king and city.',
    'Azekah': 'Dug over. A city in Judah.',
    'Makkedah': 'Place of shepherds. A Canaanite city.',
    'Anab': 'Grapes. A city in Judah.',
    'Gath': 'Winepress. A Philistine city.',
    'Megiddo': 'Place of troops. A fortress city.',
    'Shihor': 'Dark, turbid. Eastern border of Egypt.',
    'Mearah': 'Cave. A Sidonian place.',
    'Mephaath': 'Splendor. A Levitical city.',
    'Jogbehah': 'Lofty. A city in Gad.',
    'Bozkath': 'Rocky ground. A city in Judah.',
    'Cabbon': 'Understood. A city in Judah.',
    'Heshmon': 'Rich soil. A place in Judah.',
    'Secacah': 'Enclosure. A wilderness town.',
    'Nibshan': 'Prophecy. A wilderness town.',
    'Zemaraim': 'Double fleece. A city in Benjamin.',
    'Ophni': 'Mouldy. A city in Benjamin.',
    'Irpeel': 'God heals. A city in Benjamin.',
    'Taralah': 'Reeling. A city in Benjamin.',
    'Maralah': 'Trembling. A border town in Zebulun.',
    'Daberath': 'Pasture. A Levitical city in Issachar.',
    'Kattath': 'Small. A city in Zebulun.',
    'Idalah': 'God remembers. A city in Zebulun.',
    'Shunem': 'Double resting place. A city in Issachar.',
    'Kishion': 'Hard. A Levitical city.',
    'Remeth': 'Height. A city in Issachar.',
    'Beten': 'Belly, womb. A city in Asher.',
    'Mishal': 'Request. A Levitical city.',
    'Neiel': 'God moves. A border town in Asher.',
    'Cabul': 'Displeasing. A district in Galilee.',
    'Ebron': 'Variant of Hebron. Alliance.',
    'Hammon': 'Hot spring. A city in Asher.',
    'Hukok': 'Decree. A border town in Naphtali.',
    'Ziddim': 'Sides. A fortified city in Naphtali.',
    'Hammath': 'Hot spring. Near Tiberias.',
    'Eltekeh': 'God is its fear. A Levitical city.',
    'Jehud': 'Praise. A city in Dan.',
    'Rakkon': 'Thinness, narrow. A city in Dan.',
    'Timnath': 'Portion. Variant of Timnah.',
    'Kibzaim': 'Two heaps. A Levitical city.',
    'Gaash': 'Shaking, earthquake. A hill in Ephraim.',
    'Zephath': 'Watchtower. Later called Hormah.',
    'Ahlab': 'Fatness, fertile. A city in Asher.',
    'Helbah': 'Fatness. A city in Asher.',
    'Aphik': 'Fortress. A city in Asher.',
    'Shaalbim': 'Place of foxes.',
    'Sela': 'Rock. Edomite capital.',
    'Bochim': 'Weepers. Where the angel rebuked Israel.',
    'Anath': 'Answer. Father of Shamgar.',
    'Abinoam': 'Father of pleasantness.',
    'Zererah': 'Variant of Zeredah. Fortress.',
    'Tabbath': 'Celebrated. A place near the Jordan.',
    'Oreb': 'Raven. A Midianite prince.',
    'Karkor': 'Foundation. A place in Transjordan.',
    'Jotham': 'YHWH is perfect. Son of Gideon.',
    'Ebed': 'Servant. Father of Gaal.',
    'Arumah': 'Height. Near Shechem.',
    'Zalmon': 'Shady. A mount near Shechem.',
    'Thebez': 'Brightness. A city near Shechem.',
    'Dodo': 'His beloved. A judge ancestor.',
    'Kamon': 'Rising up. Where Jair was buried.',
    'Ibzan': 'Splendid. A judge from Bethlehem.',
    'Hillel': 'He praised greatly.',
    'Pirathon': 'Princely. Home of Abdon.',
    'Sorek': 'Choice vine. Valley of Sorek.',
    'Gidom': 'Cutting off. Near Gibeah.',
    'Zuphites': 'People from Zuph.',
    'Zuph': 'Honeycomb. An Ephraimite ancestor.',
    'Tohu': 'Lowly. An ancestor of Samuel.',
    'Jeshanah': 'Old. A city captured by Abijah.',
    'Nob': 'High place. A priestly city.',
    'Achish': 'Angry, serpent-like. King of Gath.',
    'Hereth': 'Forest. Where David hid.',
    'Hachilah': 'Dark. A hill in Judah.',
    'Zeruiah': 'Balsam. Mother of Joab.',
    'Maoch': 'Poor. Father of Achish.',
    'Chileab': 'Like his father. Son of David.',
    'Haggith': 'Festive. A wife of David.',
    'Abital': 'Father of dew. A wife of David.',
    'Ithream': 'Abundance of people. Son of David.',
    'Rizpah': 'Hot stone. Concubine of Saul.',
    'Gittaim': 'Two winepresses. A town in Benjamin.',
    'Shobab': 'Rebellious. A son of David.',
    'Elishua': 'God is salvation. A son of David.',
    'Uzza': 'Strength. A garden where kings were buried.',
    'Ahio': 'Brotherly. Who drove the ark cart.',
    'Uzzah': 'Strength. Who touched the ark.',
    'Berothai': 'Wells. A city of Hadadezer.',
    'Toi': 'Error, wandering. King of Hamath.',
    'Shavsha': 'Scribe. Variant of Seraiah.',
    'Benaiah': 'YHWH has built.',
    'Shobach': 'Pouring out. An Aramean commander.',
    'Eliam': 'God of the people.',
    'Uriah': 'My light is YHWH.',
    'Milcom': 'Their king. The Ammonite deity.',
    'Shimah': 'Fame, report. A brother of David.',
    'Horonaim': 'Two hollows. A Moabite city.',
    'Hushai': 'Hasty. David friend and spy.',
    'Ithra': 'Abundance. Father of Amasa.',
    'Abigal': 'Father of joy. Variant of Abigail.',
    'Shobi': 'Glorious. Who helped David.',
    'Armoni': 'Born in the palace. Son of Saul.',
    'Gob': 'Cistern. Where Philistine battles occurred.',
    'Jaare': 'Forests. Father of Elhanan.',
    'Ariel': 'Lion of God. A name for Jerusalem/altar.',
    'Elika': 'God has rejected.',
    'Ikkesh': 'Crooked. Father of Ira.',
    'Mebunnai': 'Building. One of David mighty men.',
    'Maharai': 'Swift. One of David mighty men.',
    'Azmaveth': 'Strong as death.',
    'Sharar': 'Firm. Father of Ahiam.',
    'Ahasbai': 'Blooming. Father of Eliphelet.',
    'Paarai': 'Yawning. One of David mighty men.',
    'Zelek': 'Fissure. An Ammonite warrior.',
    'Naharai': 'Snorer. Armor-bearer of Joab.',
    'Abishag': 'Father of error. A Shunammite.',
    'Zoheleth': 'Serpent. A stone near En-rogel.',
    'Azariah': 'YHWH has helped.',
    'Ahishar': 'Brother of song.',
    'Abda': 'Servant. Father of Adoniram.',
    'Iddo': 'Timely. A seer/prophet.',
    'Paruah': 'Blossoming. Father of Jehoshaphat.',
    'Geber': 'Man, hero. A district governor.',
    'Ethan': 'Enduring, permanent. A wise man.',
    'Heman': 'Faithful. A temple singer.',
    'Darda': 'Pearl of knowledge.',
    'Gebal': 'Mountain, boundary. A Phoenician city.',
    'Tadmor': 'Palm city. Palmyra in the desert.',
    'Nebat': 'Regard. Father of Jeroboam.',
    'Zeruah': 'Leprous. Mother of Jeroboam.',
    'Shishak': 'An Egyptian pharaoh.',
    'Shemaiah': 'YHWH has heard.',
    'Josiah': 'YHWH supports.',
    'Uriel': 'Light of God.',
    'Hezion': 'Vision. Grandfather of Ben-hadad.',
    'Hanani': 'Gracious. A seer.',
    'Ginath': 'Protection. Father of Tibni.',
    'Ethbaal': 'With Baal. King of Sidon.',
    'Hiel': 'God lives. Who rebuilt Jericho.',
    'Segub': 'Exalted. Son of Hiel who died.',
    'Nimshi': 'Drawn out. Grandfather of Jehu.',
    'Imlah': 'Fullness. Father of Micaiah.',
    'Zedekiah': 'YHWH is righteous.',
    'Amon': 'Faithful, trustworthy. A king of Judah.',
    'Ahaziah': 'YHWH has seized.',
    'Shilhi': 'Armed. Grandfather of Jehoshaphat.',
    'Gehazi': 'Valley of vision. Servant of Elisha.',
    'Athaliah': 'YHWH is exalted. A queen of Judah.',
    'Bidkar': 'Son of Deker. A captain of Jehu.',
    'Zibiah': 'Gazelle. Mother of King Joash.',
    'Shomer': 'Guard, watchman.',
    'Joahaz': 'YHWH has seized. Variant of Jehoahaz.',
    'Amittai': 'Truthful. Father of Jonah.',
    'Jecoliah': 'YHWH is able. Mother of Uzziah.',
    'Uzziah': 'YHWH is my strength.',
    'Remaliah': 'YHWH adorns. Father of Pekah.',
    'Arieh': 'Lion. A captain killed with Pekahiah.',
    'Hezekiah': 'YHWH strengthens.',
    'Media': 'Middle land. Kingdom of the Medes.',
    'Shebna': 'Vigor. A royal steward.',
    'Asaph': 'Gatherer. A temple singer.',
    'Isaiah': 'YHWH is salvation.',
    'Amoz': 'Strong. Father of Isaiah.',
    'Tirhakah': 'An Ethiopian/Nubian pharaoh.',
    'Haruz': 'Earnest, diligent. Grandfather of Amon.',
    'Adaiah': 'YHWH has adorned.',
    'Azaliah': 'YHWH has reserved.',
    'Michaiah': 'Who is like YHWH?',
    'Huldah': 'Weasel. A prophetess.',
    'Tikvah': 'Hope, expectation.',
    'Harhas': 'Splendor. Grandfather of Huldah.',
    'Jeremiah': 'YHWH exalts.',
    'Pedaiah': 'YHWH redeems.',
    'Rumah': 'Height. Birthplace of Zebudah.',
    'Elnathan': 'God has given.',
    'Gedaliah': 'YHWH is great.',
    'Kareah': 'Bald. Father of Johanan.',
    'Hadassah': 'Myrtle tree. Birth name of Esther.',
    'Hegai': 'Venerable. Keeper of the harem.',
    'Teresh': 'Desire. A Persian conspirator.',
    'Bildad': 'Son of contention.',
    'Zarah': 'Rising, dawning. Variant of Zerah.',
    'Shimeon': 'Hearing. Variant of Simeon.',
    'Tobijah': 'YHWH is good.',
    'Tobiah': 'YHWH is good.',
    'Oded': 'Restorer. A prophet of Samaria.',
    'Arabs': 'Desert dwellers. People of Arabia.',
    'Ammonim': 'People of Ammon.',
    'Ziz': 'A cliff, flower.',
}

fixed = 0
still_missing = []

for i, n in enumerate(names):
    if n.get('definition'):
        continue
    eng = n.get('english', '')
    heb = n.get('hebrew', '')

    if eng in MANUAL:
        names[i]['definition'] = MANUAL[eng]
        fixed += 1
    elif heb in all_by_hebrew:
        sid = all_by_hebrew[heb]
        se = strongs[sid]
        m = se.get('meaning', '') or se.get('usage', '')
        if m:
            m = re.sub(r'^[^,]+,\s*', '', m).strip()
            if m and len(m) > 2:
                names[i]['definition'] = m[0].upper() + m[1:]
                names[i]['strongs'] = sid
                if se['pron']: names[i]['pronunciation'] = se['pron']
                if se['xlit']: names[i]['transliteration'] = se['xlit']
                fixed += 1
                continue
        still_missing.append(eng)
    else:
        # Gentilics
        base = re.sub(r'(ites?|ans?|eans?|ish)$', '', eng)
        if base != eng and len(base) > 2:
            names[i]['definition'] = f'Of/from {base}.'
            fixed += 1
        else:
            still_missing.append(eng)

has_def = sum(1 for n in names if n.get('definition'))
print(f'Fixed {fixed} more names')
print(f'Still missing: {len(still_missing)}')
if still_missing:
    print(f'Missing: {still_missing}')
print(f'Final: {has_def}/{len(names)} with definitions ({has_def/len(names)*100:.1f}%)')

data['names'] = names
with open(BASE_DIR / 'data' / 'bible_names.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)
print('Saved.')
